listener 1883 0.0.0.0
allow_anonymous false

# Windows: C:\Program Files\mosquitto\mosquitto_dynamic_security.dll
# Linux: /usr/lib/x86_64-linux-gnu/mosquitto_dynamic_security.so
plugin C:\Program Files\mosquitto\mosquitto_dynamic_security.dll

# Windows: D:\mqtt\dynamic-security.json
# Linux: /home/ubuntu/mqtt/dynamic-security.json (or use relative path)
plugin_opt_config_file D:\mqtt\dynamic-security.json